In [25]:
import pandas as pd
import numpy as np

In [16]:
file = r'data\medicine_dataset.csv'
data = pd.read_csv(file)
df = pd.DataFrame(data)
df.head()

C:\Users\BIT\AppData\Local\Temp\ipykernel_28396\578920583.py:2: DtypeWarning: Columns (42,43,44,45,46,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file)

,id,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,...,sideEffect41,use0,use1,use2,use3,use4,Chemical Class,Habit Forming,Therapeutic Class,Action Class
0,1,augmentin 625 duo tablet,Penciclav 500 mg/125 mg Tablet,Moxikind-CV 625 Tablet,Moxiforce-CV 625 Tablet,Fightox 625 Tablet,Novamox CV 625mg Tablet,Vomiting,Nausea,Diarrhea,...,NaN,Treatment of Bacterial infections,NaN,NaN,NaN,NaN,NaN,No,ANTI INFECTIVES,NaN
1,2,azithral 500 tablet,Zithrocare 500mg Tablet,Azax 500 Tablet,Zady 500 Tablet,Cazithro 500mg Tablet,Trulimax 500mg Tablet,Vomiting,Nausea,Abdominal pain,...,NaN,Treatment of Bacterial infections,NaN,NaN,NaN,NaN,Macrolides,No,ANTI INFECTIVES,Macrolides
2,3,ascoril ls syrup,Solvin LS Syrup,Ambrodil-LX Syrup,Zerotuss XP Syrup,Capex LS Syrup,Broxum LS Syrup,Nausea,Vomiting,Diarrhea,...,NaN,Treatment of Cough with mucus,NaN,NaN,NaN,NaN,NaN,No,RESPIRATORY,NaN
3,4,allegra 120mg tablet,Lcfex Tablet,Etofex 120mg Tablet,Nexofex 120mg Tablet,Fexise 120mg Tablet,Histafree 120 Tablet,Headache,Drowsiness,Dizziness,...,NaN,Treatment of Sneezing and runny nose due to al...,Treatment of Allergic conditions,NaN,NaN,NaN,Diphenylmethane Derivative,No,RESPIRATORY,H1 Antihistaminics (second Generation)
4,5,avil 25 tablet,Eralet 25mg Tablet,NaN,NaN,NaN,NaN,Sleepiness,Dryness in mouth,NaN,...,NaN,Treatment of Allergic conditions,NaN,NaN,NaN,NaN,Pyridines Derivatives,No,RESPIRATORY,H1 Antihistaminics (First Generation)

In [17]:
df = df.drop('id', axis = 1)
df.head()

,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,sideEffect3,...,sideEffect41,use0,use1,use2,use3,use4,Chemical Class,Habit Forming,Therapeutic Class,Action Class
0,augmentin 625 duo tablet,Penciclav 500 mg/125 mg Tablet,Moxikind-CV 625 Tablet,Moxiforce-CV 625 Tablet,Fightox 625 Tablet,Novamox CV 625mg Tablet,Vomiting,Nausea,Diarrhea,NaN,...,NaN,Treatment of Bacterial infections,NaN,NaN,NaN,NaN,NaN,No,ANTI INFECTIVES,NaN
1,azithral 500 tablet,Zithrocare 500mg Tablet,Azax 500 Tablet,Zady 500 Tablet,Cazithro 500mg Tablet,Trulimax 500mg Tablet,Vomiting,Nausea,Abdominal pain,Diarrhea,...,NaN,Treatment of Bacterial infections,NaN,NaN,NaN,NaN,Macrolides,No,ANTI INFECTIVES,Macrolides
2,ascoril ls syrup,Solvin LS Syrup,Ambrodil-LX Syrup,Zerotuss XP Syrup,Capex LS Syrup,Broxum LS Syrup,Nausea,Vomiting,Diarrhea,Upset stomach,...,NaN,Treatment of Cough with mucus,NaN,NaN,NaN,NaN,NaN,No,RESPIRATORY,NaN
3,allegra 120mg tablet,Lcfex Tablet,Etofex 120mg Tablet,Nexofex 120mg Tablet,Fexise 120mg Tablet,Histafree 120 Tablet,Headache,Drowsiness,Dizziness,Nausea,...,NaN,Treatment of Sneezing and runny nose due to al...,Treatment of Allergic conditions,NaN,NaN,NaN,Diphenylmethane Derivative,No,RESPIRATORY,H1 Antihistaminics (second Generation)
4,avil 25 tablet,Eralet 25mg Tablet,NaN,NaN,NaN,NaN,Sleepiness,Dryness in mouth,NaN,NaN,...,NaN,Treatment of Allergic conditions,NaN,NaN,NaN,NaN,Pyridines Derivatives,No,RESPIRATORY,H1 Antihistaminics (First Generation)

In [18]:
print("Data Shape: ", df.shape)

Data Shape:  (248218, 57)

In [19]:
initial_features = df.columns
print("Initial feature: ", initial_features)

Initial feature:  Index(['name', 'substitute0', 'substitute1', 'substitute2', 'substitute3',
       'substitute4', 'sideEffect0', 'sideEffect1', 'sideEffect2',
       'sideEffect3', 'sideEffect4', 'sideEffect5', 'sideEffect6',
       'sideEffect7', 'sideEffect8', 'sideEffect9', 'sideEffect10',
       'sideEffect11', 'sideEffect12', 'sideEffect13', 'sideEffect14',
       'sideEffect15', 'sideEffect16', 'sideEffect17', 'sideEffect18',
       'sideEffect19', 'sideEffect20', 'sideEffect21', 'sideEffect22',
       'sideEffect23', 'sideEffect24', 'sideEffect25', 'sideEffect26',
       'sideEffect27', 'sideEffect28', 'sideEffect29', 'sideEffect30',
       'sideEffect31', 'sideEffect32', 'sideEffect33', 'sideEffect34',
       'sideEffect35', 'sideEffect36', 'sideEffect37', 'sideEffect38',
       'sideEffect39', 'sideEffect40', 'sideEffect41', 'use0', 'use1', 'use2',
       'use3', 'use4', 'Chemical Class', 'Habit Forming', 'Therapeutic Class',
       'Action Class'],
      dtype='object')

In [20]:
df['Substitutes'] = df[['substitute0', 'substitute1', 'substitute2', 'substitute3', 'substitute4']] \
                    .astype(str)\
                    .agg(', '.join, axis=1)

df['Side Effects'] = df[['sideEffect0', 'sideEffect1', 'sideEffect2',
       'sideEffect3', 'sideEffect4', 'sideEffect5', 'sideEffect6',
       'sideEffect7', 'sideEffect8', 'sideEffect9', 'sideEffect10',
       'sideEffect11', 'sideEffect12', 'sideEffect13', 'sideEffect14',
       'sideEffect15', 'sideEffect16', 'sideEffect17', 'sideEffect18',
       'sideEffect19', 'sideEffect20', 'sideEffect21', 'sideEffect22',
       'sideEffect23', 'sideEffect24', 'sideEffect25', 'sideEffect26',
       'sideEffect27', 'sideEffect28', 'sideEffect29', 'sideEffect30',
       'sideEffect31', 'sideEffect32', 'sideEffect33', 'sideEffect34',
       'sideEffect35', 'sideEffect36', 'sideEffect37', 'sideEffect38',
       'sideEffect39', 'sideEffect40', 'sideEffect41']].astype(str).agg(', '.join, axis = 1)

df['Uses'] = df[['use0', 'use1', 'use2', 'use3', 'use4']].astype(str).agg(', '.join, axis = 1)

In [21]:
df.head()

,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,sideEffect3,...,use2,use3,use4,Chemical Class,Habit Forming,Therapeutic Class,Action Class,Substitutes,Side Effects,Uses
0,augmentin 625 duo tablet,Penciclav 500 mg/125 mg Tablet,Moxikind-CV 625 Tablet,Moxiforce-CV 625 Tablet,Fightox 625 Tablet,Novamox CV 625mg Tablet,Vomiting,Nausea,Diarrhea,NaN,...,NaN,NaN,NaN,NaN,No,ANTI INFECTIVES,NaN,"Penciclav 500 mg/125 mg Tablet, Moxikind-CV 62...","Vomiting, Nausea, Diarrhea, nan, nan, nan, nan...","Treatment of Bacterial infections, nan, nan, n..."
1,azithral 500 tablet,Zithrocare 500mg Tablet,Azax 500 Tablet,Zady 500 Tablet,Cazithro 500mg Tablet,Trulimax 500mg Tablet,Vomiting,Nausea,Abdominal pain,Diarrhea,...,NaN,NaN,NaN,Macrolides,No,ANTI INFECTIVES,Macrolides,"Zithrocare 500mg Tablet, Azax 500 Tablet, Zady...","Vomiting, Nausea, Abdominal pain, Diarrhea, na...","Treatment of Bacterial infections, nan, nan, n..."
2,ascoril ls syrup,Solvin LS Syrup,Ambrodil-LX Syrup,Zerotuss XP Syrup,Capex LS Syrup,Broxum LS Syrup,Nausea,Vomiting,Diarrhea,Upset stomach,...,NaN,NaN,NaN,NaN,No,RESPIRATORY,NaN,"Solvin LS Syrup, Ambrodil-LX Syrup, Zerotuss X...","Nausea, Vomiting, Diarrhea, Upset stomach, Sto...","Treatment of Cough with mucus, nan, nan, nan, nan"
3,allegra 120mg tablet,Lcfex Tablet,Etofex 120mg Tablet,Nexofex 120mg Tablet,Fexise 120mg Tablet,Histafree 120 Tablet,Headache,Drowsiness,Dizziness,Nausea,...,NaN,NaN,NaN,Diphenylmethane Derivative,No,RESPIRATORY,H1 Antihistaminics (second Generation),"Lcfex Tablet, Etofex 120mg Tablet, Nexofex 120...","Headache, Drowsiness, Dizziness, Nausea, nan, ...",Treatment of Sneezing and runny nose due to al...
4,avil 25 tablet,Eralet 25mg Tablet,NaN,NaN,NaN,NaN,Sleepiness,Dryness in mouth,NaN,NaN,...,NaN,NaN,NaN,Pyridines Derivatives,No,RESPIRATORY,H1 Antihistaminics (First Generation),"Eralet 25mg Tablet, nan, nan, nan, nan","Sleepiness, Dryness in mouth, nan, nan, nan, n...","Treatment of Allergic conditions, nan, nan, na..."

In [22]:
keep_cols = ['name', 'Chemical Class', 'Habit Forming', 'Therapeutic Class', 'Action Class']

features_to_drop = [cols for cols in initial_features.tolist() if cols not in keep_cols]

In [23]:
df = df.drop(columns = features_to_drop, axis = 1)
df.head()

,name,Chemical Class,Habit Forming,Therapeutic Class,Action Class,Substitutes,Side Effects,Uses
0,augmentin 625 duo tablet,NaN,No,ANTI INFECTIVES,NaN,"Penciclav 500 mg/125 mg Tablet, Moxikind-CV 62...","Vomiting, Nausea, Diarrhea, nan, nan, nan, nan...","Treatment of Bacterial infections, nan, nan, n..."
1,azithral 500 tablet,Macrolides,No,ANTI INFECTIVES,Macrolides,"Zithrocare 500mg Tablet, Azax 500 Tablet, Zady...","Vomiting, Nausea, Abdominal pain, Diarrhea, na...","Treatment of Bacterial infections, nan, nan, n..."
2,ascoril ls syrup,NaN,No,RESPIRATORY,NaN,"Solvin LS Syrup, Ambrodil-LX Syrup, Zerotuss X...","Nausea, Vomiting, Diarrhea, Upset stomach, Sto...","Treatment of Cough with mucus, nan, nan, nan, nan"
3,allegra 120mg tablet,Diphenylmethane Derivative,No,RESPIRATORY,H1 Antihistaminics (second Generation),"Lcfex Tablet, Etofex 120mg Tablet, Nexofex 120...","Headache, Drowsiness, Dizziness, Nausea, nan, ...",Treatment of Sneezing and runny nose due to al...
4,avil 25 tablet,Pyridines Derivatives,No,RESPIRATORY,H1 Antihistaminics (First Generation),"Eralet 25mg Tablet, nan, nan, nan, nan","Sleepiness, Dryness in mouth, nan, nan, nan, n...","Treatment of Allergic conditions, nan, nan, na..."

In [26]:
df.replace(np.nan, '', inplace = True)
df.head()

,name,Chemical Class,Habit Forming,Therapeutic Class,Action Class,Substitutes,Side Effects,Uses
0,augmentin 625 duo tablet,,No,ANTI INFECTIVES,,"Penciclav 500 mg/125 mg Tablet, Moxikind-CV 62...","Vomiting, Nausea, Diarrhea, nan, nan, nan, nan...","Treatment of Bacterial infections, nan, nan, n..."
1,azithral 500 tablet,Macrolides,No,ANTI INFECTIVES,Macrolides,"Zithrocare 500mg Tablet, Azax 500 Tablet, Zady...","Vomiting, Nausea, Abdominal pain, Diarrhea, na...","Treatment of Bacterial infections, nan, nan, n..."
2,ascoril ls syrup,,No,RESPIRATORY,,"Solvin LS Syrup, Ambrodil-LX Syrup, Zerotuss X...","Nausea, Vomiting, Diarrhea, Upset stomach, Sto...","Treatment of Cough with mucus, nan, nan, nan, nan"
3,allegra 120mg tablet,Diphenylmethane Derivative,No,RESPIRATORY,H1 Antihistaminics (second Generation),"Lcfex Tablet, Etofex 120mg Tablet, Nexofex 120...","Headache, Drowsiness, Dizziness, Nausea, nan, ...",Treatment of Sneezing and runny nose due to al...
4,avil 25 tablet,Pyridines Derivatives,No,RESPIRATORY,H1 Antihistaminics (First Generation),"Eralet 25mg Tablet, nan, nan, nan, nan","Sleepiness, Dryness in mouth, nan, nan, nan, n...","Treatment of Allergic conditions, nan, nan, na..."

In [ ]:
df['Substitutes'] = df['Substitutes'].str.replace('nan', '', regex = False).str.replace(r'(,\s*)+', ', ', regex = True).str.strip(', ')
df['Side Effects'] = df['Side Effects'].str.replace('nan', '', regex = False).str.replace(r'(,\s*)+', ', ', regex = True).str.strip(', ')
df['Uses'] = df['Uses'].str.replace('nan', '', regex = False).str.replace(r'(,\s*)+', ', ', regex = True).str.strip(', ')
df.head()

,name,Chemical Class,Habit Forming,Therapeutic Class,Action Class,Substitutes,Side Effects,Uses
0,augmentin 625 duo tablet,,No,ANTI INFECTIVES,,"Penciclav 500 mg/125 mg Tablet, Moxikind-CV 62...","Vomiting, Nausea, Diarrhea",Treatment of Bacterial infections
1,azithral 500 tablet,Macrolides,No,ANTI INFECTIVES,Macrolides,"Zithrocare 500mg Tablet, Azax 500 Tablet, Zady...","Vomiting, Nausea, Abdominal pain, Diarrhea",Treatment of Bacterial infections
2,ascoril ls syrup,,No,RESPIRATORY,,"Solvin LS Syrup, Ambrodil-LX Syrup, Zerotuss X...","Nausea, Vomiting, Diarrhea, Upset stomach, Sto...",Treatment of Cough with mucus
3,allegra 120mg tablet,Diphenylmethane Derivative,No,RESPIRATORY,H1 Antihistaminics (second Generation),"Lcfex Tablet, Etofex 120mg Tablet, Nexofex 120...","Headache, Drowsiness, Dizziness, Nausea",Treatment of Sneezing and runny nose due to al...
4,avil 25 tablet,Pyridines Derivatives,No,RESPIRATORY,H1 Antihistaminics (First Generation),Eralet 25mg Tablet,"Sleepiness, Dryness in mouth",Treatment of Allergic conditions

In [36]:
df.to_csv("./data/Preprocessed Medicine Dataset.csv", index = False)